---
title: "Lefkios Paikousis"
description: |
  A shot summary
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


I am very fond of data analysis, visualisation, statistical modelling, automation and building interactive web applications. I am dedicated to turning research and business data into knowledge.

I collaborate with both the private sector, for data analysis - statistical programming - visualisation, and academic researchers with survey design and analysis.

My core competencies are:

* Statistical computing: I can identify and analyze trends or patterns in data sets through the use of the [statistical computing language R](https://www.r-project.org/).

* Reproducibility: I can create reports in Rmarkdown documents. Rmarkdown enables reproducibility and knowledge sharing in an effective manner.

* Data and database wrangling: I have extensive knowledge of the dplyr package in R. Dplyr is the grammar of data manipulation and part of the tidyverse collection of R packages designed for data science.

* Visualisations: Very good knowledge of the ggplot2 package in R. Ggplot2 is an advanced plotting system for R based on the grammar of graphics.

* Web applications: I build interactive web apps using the [shiny framework](https://shiny.rstudio.com)

* Excel Modelling: Developed the [ImproRisk model](www.improrisk.com) - a tool for conducting deterministic dietary risk assessment analysis. It is built in MS Excel utilising a series of excel functions and VBA syntax. It is now being used by several European risk assessment authorities.

* Training: Im an accredited trainer by the [Cyprus Authority of the Developemnt of Human Resources](https://www.anad.org.cy)

* Survey design, data collection and analysis: Expertise in designing surveys. Implement data collection processes, data cleaning, validation and final preparation for analysis. 

* Research. As an independent researcher, I collaborate with academia in the area of healthcare.


### Contact

You can send me an email: lefkiospaikousis@yahoo.com
